version: '3'
services:
  app:
    build:
      ./
    working_dir:
      /var/www/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command:
      /bin/sh -c "npm install && npm start"
